//
//
//  Generated by StarUML(tm) Java Add-In
//
//  Caleb Dusenbery
//  trackCom.java 
//
//





public class trackCom {
	public String theLine;
	public double position;
	public int block;
	public int lastBlock;
	public double grade;
	public double elevation;
	public double blockLength;
	public TrackModel theTrack;

	public trackCom(TrackModel newroute, String line, int firstblock){
		theTrack = newroute;
		theLine = line;
		block = firstblock;
		lastBlock = 0;
		getTrackInfo();
		theTrack.occupyBlock(theLine, block);
	}
	
	public void initialBlock(String lineName){
		/*
		//maybe not used anymore
		if(lineName.equals("Red"){
			//block = 9;
		}else{
			block = 62;
		}
		*/
	}
	public void getTrackInfo() {
		
		//theTrack.next(theLine, block, lastBlock);
		
		
		blockLength = theTrack.blockLength(theLine, block);
		grade = theTrack.blockGrade(theLine, block);
		//elevation = theTrack.blockLength(line, block);
		
	}
	
	public void checkBlock(double distance) {
		position += distance;
		System.out.println("\nposition: " + position);
		if(position > blockLength){
			
			position = position - blockLength;
			getNextBlock();//int or what???
		}
	
	
	}
	
	public void getNextBlock() {
		int curblock = block;
		block = theTrack.next(theLine, block, lastBlock);
		lastBlock = curblock;
		System.out.println("I'm on " + block);
		getTrackInfo();
		theTrack.occupyBlock(theLine, lastBlock, block);
	}
}
